/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socialNetwork;

import com.google.common.graph.*;
import com.google.gson.Gson;

import javax.print.DocFlavor;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.Vector;


public class App {

    

    public static void writePerson(Person person) throws IOException {

        Gson gson = new Gson();
        String json = gson.toJson(person);

        FileWriter writer = new FileWriter("app/src/main/java/people");
        writer.close();

    }

    public static Person readPerson(String file_name) throws IOException {
        Gson gson = new Gson();
        FileReader reader = new FileReader(file_name);
        reader.read();
        Person poop = gson.fromJson(reader, Person.class);



        System.out.println(poop.getName());

        return poop;


    }

    public static void writeNetwork(MutableNetwork<Person,Person> network) throws IOException {

        Gson gson = new Gson();
        String json = gson.toJson(network);

        FileWriter writer = new FileWriter("app/src/main/java/network");
        writer.close();

    }



    public Person getNewPerson(MutableNetwork<Person,Person> network) {
        Scanner input = new Scanner(System.in);
        System.out.println("Enter the name of the Person");
        String name = input.nextLine();

        Person new_person = new Person(name);
        network.addNode(new_person);
        return new_person;
    }




    public static void main(String[] args) throws IOException {

        Person eduardo = new Person("eduardo");
        writePerson(eduardo);
        Person new_eduardo = readPerson("app/src/main/java/network");
        System.out.println(new_eduardo.toString());





    }
}
