/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poop;

import com.google.common.graph.*;
import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;


public class App {

    private NetworkBuilder<Object, Object> relationship_network = NetworkBuilder.directed();
    

    public static void writeFile(NetworkBuilder<Object, Object> graph) throws IOException {

        Gson gson = new Gson();
        String json = gson.toJson(graph);

        FileWriter writer = new FileWriter("./" + "relationshipdata.json");
        writer.write(json);
        writer.close();

    }

//    public NetworkBuilder<Object, Object> readFile() throws IOException {
//        Gson gson = new Gson();
//
//        FileReader reader = new FileReader("./" + "relationshipdata.json");
//        String relationship_data = String.valueOf(reader.read());
//        relationship_data = gson.fromJson(relationship_data);
//
//    }

    public Person getNewPerson() {
        Scanner input = new Scanner(System.in);
        System.out.println("Enter the name of the Person");
        String name = input.nextLine();

        Person new_person = new Person(name);
        relationship_network.addNode(new_person);
        return new_person;
    }

    public void addRelationship() {
        
    }


    public static void main(String[] args) throws IOException {







    }
}
